modify pressure_sore and create new pain_scale_enhanced field
coronasafe/care pull request #1016
Opened 2022-09-09 07:14 UTC by Pragati1610

fixes https://github.com/coronasafe/care_fe/issues/3556

## Changes

- pain scale in Vitals need the properties of region and scale similar to pressure sore section
- Add description fields for each region in pressure sore section in Record updates
- Add description fields for each region in pain scale in Vitals [Record updates]

@coronasafe/care-developers

2022-09-09 10:11 UTC, sainak commented
@Pragati1610 rebase your changes on care/master branch

2022-09-09 11:21 UTC, Pragati1610 commented
okay

2022-09-09 14:29 UTC, gigincg commented
@Pragati1610 What did you modify in Pressure Sores?

2022-09-09 16:46 UTC, Pragati1610 commented
> @Pragati1610 What did you modify in Pressure Sores?

Added description field

2022-09-10 15:58 UTC, vigneshhari requested changes

2022-09-10 15:58 UTC, vigneshhari commented on docker/.local.env
> +JWKS_BASE64=eyJrZXlzIjogW3sibiI6ICI2Q1Q5ZkZRRkFNSENIN3JyVFFHeFlfX2NOWXJkWkdwWG5MSU9uaTU3VHpTbHZqako5Z0lpWGVhaDVUNEIyVEc2R1oxZU5Fc2FYQ2Y5Y09QVi1jQzNEbzQyd2k4SnEyM0lNWHhlb3dNcE9QYng2TVczb1FpeHZxU2ZZay1
This is an unrelated change, remove this.

2022-09-16 18:08 UTC, vigneshhari approved these changes

2022-09-16 18:09 UTC, merged