return internal name in file list to make determining the file extens…
coronasafe/care pull request #1019
Opened 2022-09-09 17:57 UTC by sainak

…ion easier

## Proposed Changes

internal_name is required to determine the file type based on the file extension

@coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

2022-09-10 15:53 UTC, vigneshhari requested changes
Let's not give the internal name out, our goal here was to break the relationship between the file name and the patient in the unlikely case our buckets are attacked. 
Let's serialize only the extension.

2022-09-10 18:28 UTC, sainak commented
> Let's not give the internal name out, our goal here was to break the relationship between the file name and the patient in the unlikely case our buckets are attacked. Let's serialize only the extension.

yeah I thought returning the extension would be a better solution
do you have any suggestions for implementing that?
I have 2 implementations in mind 
- making the query return the extension
- make a model method to return extension or file type

2022-09-10 20:51 UTC, vigneshhari commented
the model method sounds good enough. make sure you handle the edge cases.

2022-09-14 14:18 UTC, vigneshhari approved these changes

2022-09-14 14:18 UTC, merged