Fixed: Added occupation field for text support
coronasafe/care pull request #1058
Opened 2022-10-09 04:47 UTC by cp-Coder

# Updates

- [x] Fixes #806
- [x] Removed `Occupation Choices` from `PatientMetaInfo` model
- [x] Altered the occupation field from `IntegerField` to `CharField`
- [x] Removed occupation field as `ChoiceField` from `PatientMetaInfoSerializer`
- [x] Added migration to alter the schema for `occupation` field
- [x] Added migration to retain all the data

2022-10-10 18:47 UTC, vigneshhari requested changes

2022-10-10 18:47 UTC, vigneshhari commented on care/facility/migrations/0315_auto_20220905_1008.py
> +        patient.meta_info.occupation = occupation["occupation"][1]
Need to handle cases where meta information is not present.

2022-10-10 18:47 UTC, vigneshhari commented on care/facility/migrations/0315_auto_20220905_1008.py
> +                "occupation": OccupationChoices[patient.meta_info.occupation],
Need to handle cases where meta info is not present, since its a nullable field.

2023-02-13 14:10 UTC, nihal467 commented
@vigneshhari can you review it

2023-07-20 13:47 UTC, sainak requested changes
The migrations can be improved


- create the new occupation field with name `occupation_char`
- use the PatientMetaInfo directly to get all objects
- populate the occupation_char field and add the objects to a list
- bulk update the PatientMetaInfo objects
- remove the old occupation field
- rename the occupation field

2023-07-20 16:27 UTC, sainak commented
@cp-Coder add test cases

2023-08-07 08:52 UTC, cp-Coder commented
Will open a new PR

2023-08-07 08:52 UTC, closed without merging