Fixed: Added depth in consultation model for symptoms
coronasafe/care pull request #1063
Opened 2022-10-14 08:33 UTC by cp-Coder

# Updates

- [x] Fixes #1031
- [x] Added `symptoms` model with desired fields
- [x] Removed old fields from `consultation` model
- [x] Added `is_asymptomatic` field to `consultation` model
- [x] Added migration for change in models
- [x] Added method to migrate the previous data
- [x] Added serializer for `symptoms` model
- [x] Updated serializer for `consultation` model
- [x] Reformatted the code

2022-10-14 10:21 UTC, rithviknishad commented
Required by: https://github.com/coronasafe/care_fe/issues/3618

2022-10-16 18:04 UTC, vigneshhari requested changes

2022-10-16 18:04 UTC, vigneshhari commented on care/facility/models/patient_consultation.py
> +class PatientConsultationSymptom(models.Model):
Switch to using the base model likw all other models.

2022-10-16 18:04 UTC, vigneshhari commented on care/facility/models/patient_consultation.py
> +                fields=["consultation", "symptom"],
could symptoms re appear in a single consultation?

2023-11-22 15:48 UTC, closed without merging