feat: Added more field in consultation form
coronasafe/care pull request #1073
Opened 2022-10-22 03:34 UTC by cp-Coder

# Updates

- [x] Fixes #859
- [x] Related to coronasafe/care_fe#2218, coronasafe/care_fe#2738
- [x] Added fields required in coronasafe/care_fe#3332
- [x] Added fields required in coronasafe/care_fe#3333
- [x] Added fields required in coronasafe/care_fe#3335
- [x] Added fields required in coronasafe/care_fe#3336
- [x] Added fields required in coronasafe/care_fe#3338
- [x] Added fields required in coronasafe/care_fe#3338

2022-10-22 03:57 UTC, cp-Coder commented
**SWAGGER DOCUMENTATION**
- [x] HEALTH DETAILS
![image](https://user-images.githubusercontent.com/77210185/197318013-494bb7a5-160b-4519-b98b-a96a87d771fc.png)
- [x] MEDICAL HISTORY
![image](https://user-images.githubusercontent.com/77210185/197318026-f2484f91-8666-4411-afcd-d7dc40b4219b.png)

2022-12-19 12:48 UTC, vigneshhari requested changes

2022-12-19 12:48 UTC, vigneshhari commented on care/facility/api/serializers/patient_consultation.py
> +            medical_history_serializer.is_valid(raise_exception=True)
Everything needs to be in an atomic block

2022-12-19 12:48 UTC, vigneshhari commented on care/facility/api/serializers/patient_consultation.py
> +                    "patient": consultation.patient.external_id.hex,
why is this data resupplied ?

2022-12-19 12:48 UTC, vigneshhari commented on care/facility/api/serializers/patient_consultation.py
> +                    "patient": consultation.patient.external_id.hex,
This should already be present in the object right?

2022-12-19 12:48 UTC, vigneshhari commented on care/facility/api/serializers/patient_consultation.py
> +        health_details_data = validated_data.pop("new_health_details", None)
`None` cannot be unpacked, try something that resembles the actual data's type

2022-12-19 12:48 UTC, vigneshhari commented on care/facility/api/serializers/patient_consultation.py
> +            medical_history_serializer.is_valid(raise_exception=True)
Make sure everything is in an atomic transaction

2022-12-19 12:48 UTC, vigneshhari commented on care/facility/api/serializers/patient_consultation.py
> +            if consultation.patient.last_consultation is None:
How would this situation arise?

2022-12-19 12:48 UTC, vigneshhari commented on care/facility/models/patient.py
> +    facility = models.ForeignKey(
consultation is already 1-1 tied to a facility. consultation is also tied 1-1 to a patient

2022-12-25 12:44 UTC, cp-Coder commented
@vigneshhari I have resolved all the requested changes and the PR is good for testing

2023-03-01 15:04 UTC, khavinshankar reviewed
@cp-Coder 

erroring out while migrating, can you check it out
![image](https://user-images.githubusercontent.com/29787772/222178696-d33f51e9-10c6-41e8-9c33-6537b1f85cb0.png)

2023-03-04 12:18 UTC, cp-Coder commented
@khavinshankar The issue has been fixed

2023-03-07 07:56 UTC, khavinshankar reviewed
@abhiabhi94 migrations looks good,

@nihal467 can you check it end to end

2023-03-14 12:11 UTC, khavinshankar commented
@cp-Coder I'm getting this error, after migration,
![image](https://user-images.githubusercontent.com/29787772/224997107-5d64df53-1d96-4d9d-bf62-3ac5ed976ddd.png)

2023-03-14 14:22 UTC, gigincg commented
@khavinshankar If you can add the steps to reproduce as well, @cp-Coder Might be able to debug easier 🚀

2023-03-14 14:32 UTC, khavinshankar commented
@cp-Coder To Reproduce the above issue,
Step 1: Clone the repo `git clone git@github.com:coronasafe/care_fe.git`
Step 2: Run the app `sudo make up`
Step 3: Seed dummy data `sudo docker exec care python3 manage.py load_dummy_data`
Step 4: Pull the changes from this pr `gh pr checkout 1073`
Step 5: Migrate the data, `sudo docker exec care python3 manage.py migrate`
Step 6: Try serializing patient instance in django shell `sudo docker exec -it care python3 manage.py shell`
 ```py
from care.facility.models.patient import PatientRegistration
from care.facility.api.serializers import PatientDetailsSerializer
PatientDetailsSerializer(PatientRegistration.objects.first())
 ```
 
 cc: @gigincg

2023-03-14 15:13 UTC, khavinshankar commented
@nihal467 had a huddle with @cp-Coder, everything is working fine, and there was no error, I passed in the PatientRegistration model inside PatientConsultationSerializer

@gigincg @vigneshhari can you review this and merge it

2023-10-16 09:10 UTC, closed without merging