Resize facility cover image before upload
coronasafe/care pull request #1106
Opened 2022-11-23 07:19 UTC by khavinshankar

## Proposed Changes

- resize facility cover images before uploading to s3
- set a maximum size limit of 1MB which is checked after resizing

### Associated Issue
  - Fixes https://github.com/coronasafe/care/issues/1105

### Architecture changes
  - nil
 
@coronasafe/code-reviewers

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete

2022-12-19 12:34 UTC, vigneshhari requested changes

2022-12-19 12:34 UTC, vigneshhari commented on care/facility/api/serializers/facility.py
> +        img.thumbnail((720, 720))
can we only allow images of this ratio to be uploaded in the FE? ( Square ) Anything not in this ration would look weird right?

2022-12-19 12:34 UTC, vigneshhari commented on care/facility/api/serializers/facility.py
> +            "JPEG" if image_extension.lower() == "jpg" else image_extension.upper()
why are we moving to uppercase?

2023-01-22 09:51 UTC, vigneshhari commented
This PR will be marked stale and closed within the next 2 days.

2023-04-06 06:59 UTC, gigincg commented
@khavinshankar

2023-07-05 13:50 UTC, sainak commented
can we add a basic image tool to crop and resize the image, and then just check the size at the backend
@vigneshhari

2023-08-08 18:41 UTC, closed without merging