Feat: Add a consultation_status field in consultation model
coronasafe/care pull request #1143
Opened 2023-01-04 11:32 UTC by cp-Coder

# Feature Request

## Proposed Changes

- Added a `consultation_status` field of type `IntegerField` in consultation model

## Associated Issue

- Fixes #1142

## Architecture changes

- N/A

@coronasafe/code-reviewers

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [x] Linting Complete

2023-01-12 14:39 UTC, vigneshhari requested changes

2023-01-12 14:39 UTC, vigneshhari commented on care/facility/models/patient_consultation.py
> +        default=ConsultationStatusEnum.TRANSFERRED_FROM_WARD.value,
default should be unkown

2023-01-13 05:15 UTC, nihal467 commented
@cp-Coder what is the status of this PR

2023-01-14 07:13 UTC, nihal467 commented
@vigneshhari @gigincg can you review it

2023-01-15 14:21 UTC, vigneshhari approved these changes

2023-01-19 01:17 UTC, merged