Hcx Refactors
coronasafe/care pull request #1229
Opened 2023-03-24 08:13 UTC by khavinshankar

## Proposed Changes

- Added authorization based on roles for hcx.claim and hcx.policy
- Added authentication for hcx listener apis
- Added suggestions made in #1219 

 
@coronasafe/code-reviewers

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete

2023-04-21 08:29 UTC, vigneshhari commented
Fix conflicts

2023-08-03 13:14 UTC, sainak requested changes

2023-08-03 13:14 UTC, sainak commented on config/authentication.py
> +        return token.replace("Bearer", "").replace(" ", "")
```suggestion
        return token.replace("Bearer ", "", 1)
```
and raise TokenError if the result is empty string

2023-08-03 13:14 UTC, sainak commented on config/authentication.py
> +            return None
this can be removed, in favor of token error in `get_jwt_token`

2023-08-03 13:14 UTC, sainak commented on config/authentication.py
> +class HCXAuthentication(JWTAuthentication):
add a simple schema definition class for swagger [ref](https://drf-spectacular.readthedocs.io/en/latest/customization.html?highlight=OpenApiAuthenticationExtension#specify-authentication-with-openapiauthenticationextension)

similar to
https://github.com/coronasafe/care/blob/0143084df7e994e2a45624a8ce684880782f1bf2/config/authentication.py#L272-L289

2023-08-10 14:24 UTC, Ashesh3 approved these changes

2023-09-28 21:47 UTC, sainak approved these changes

2024-08-23 07:49 UTC, khavinshankar commented
Closing this PR as this will be added as a part of HCX Plug PR

2024-08-23 07:49 UTC, closed without merging