remove HBA1C field from consultation model
coronasafe/care pull request #1309
Opened 2023-05-23 11:02 UTC by sainak

### Associated Issue
  - Fixes #1200

@coronasafe/code-reviewers

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete

2023-06-11 12:08 UTC, vigneshhari commented
Can i get an ops confirmation for this? This would remove all historical data for this field. 
cc @gigincg @aparnacoronasafe

2023-06-11 12:09 UTC, vigneshhari requested changes

2023-06-11 12:09 UTC, vigneshhari commented on care/users/management/commands/populate_investigations.py
> -HbA1C	%	4-5.6 %	4	5.6	Float		2
This can remain i guess, this is used in investigations, cc @gigincg

2023-07-20 13:05 UTC, rithviknishad approved these changes

2023-07-20 15:53 UTC, vigneshhari approved these changes

2023-07-20 15:59 UTC, merged