made patient notes consultation specific
coronasafe/care pull request #1469
Opened 2023-07-22 07:04 UTC by Bhavik-ag

## Proposed Changes

- Added new field `consultation` in patient notes model
- Added filter in patient notes based on consultation external id
- Added tests for the same

### Associated Issue

fixed #1210 

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2023-07-25 11:37 UTC, Bhavik-ag commented
@sainak please review this  PR

2023-07-26 07:38 UTC, sainak requested changes

2023-07-26 07:38 UTC, sainak commented on care/facility/api/viewsets/patient.py
> +
this is not the way to handle optional fields

2023-07-26 07:38 UTC, sainak commented on care/facility/api/viewsets/patient.py
> +
use serializers

2023-07-26 07:38 UTC, sainak commented on care/facility/api/viewsets/patient.py
> +            consultation=consultation,
to be handled in serializers

2023-07-27 04:47 UTC, rithviknishad approved these changes

2023-07-27 18:11 UTC, rithviknishad commented on care/facility/models/patient.py
> +    )
@sainak should we index this field?

2023-08-09 09:15 UTC, sainak commented on care/facility/models/patient.py
> +    )
Index for FK is enabled by default

2023-08-09 09:16 UTC, rithviknishad commented on care/facility/models/patient.py
> +    )
owuuu oki

2023-11-23 13:14 UTC, closed without merging