Ignore admission date during discharge process if not provided
coronasafe/care pull request #1475
Opened 2023-07-25 10:15 UTC by Ashesh3

## Proposed Changes

This pull request introduces a change that allows the discharge process to ignore the admission date if it's not provided. This avoids potential validation errors and exceptions during the discharge process when the admission date is absent.

- Modified the validation logic in patient_consultation.py to check if the admission date exists before comparing it with the death date.

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2023-07-25 10:36 UTC, rithviknishad approved these changes

2023-07-26 07:33 UTC, sainak approved these changes

2023-07-26 07:35 UTC, sainak commented
Also fixes https://coronasafe-network.sentry.io/issues/4306016273/

2023-07-27 07:53 UTC, rithviknishad requested changes
See #1480

2023-07-27 08:02 UTC, Ashesh3 commented
> See #1480

Fixed.

2023-07-27 08:08 UTC, rithviknishad approved these changes

2023-07-27 09:15 UTC, merged