Don't allow negative values for Doctor Count for facility
coronasafe/care pull request #1505
Opened 2023-08-02 21:46 UTC by Pranshu1902

## Proposed Changes

 Raise Validation error when user tries to give a negative value for the doctor count for a facility.

### Associated Issue

#1504 

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2023-08-03 19:16 UTC, Pranshu1902 commented
> use min value validator in the model itself

Done!

2023-08-04 04:06 UTC, rithviknishad requested changes
No migrations????

2023-08-04 05:28 UTC, sainak commented
> No migrations????

yes migrations will be required

2023-08-04 08:00 UTC, rithviknishad commented
@Pranshu1902 rebase and then make migrations

2023-08-04 11:31 UTC, Pranshu1902 commented
Added migrations @sainak @rithviknishad

2023-08-04 11:38 UTC, sainak commented on care/facility/migrations/0375_alter_dailyround_resp_alter_hospitaldoctors_count.py
> +        ),
Tis was already merged, can you delete this file and run make migrations after merging the latest master

2023-08-08 18:21 UTC, vigneshhari commented
Switch to https://docs.djangoproject.com/en/4.2/ref/models/fields/#positiveintegerfield

2023-08-08 18:54 UTC, sainak commented
> Switch to [docs.djangoproject.com/en/4.2/ref/models/fields/#positiveintegerfield](https://docs.djangoproject.com/en/4.2/ref/models/fields/#positiveintegerfield)

@Pranshu1902 make sure to handle negative values while migrating

2023-08-15 14:35 UTC, Pranshu1902 commented
@vigneshhari @sainak updated!

2023-08-18 06:59 UTC, sainak approved these changes

2023-10-20 09:08 UTC, Pranshu1902 commented
@sainak @vigneshhari please review and merge the PR

2023-10-20 09:11 UTC, sainak commented
@Pranshu1902 delete and recreate the migrations

2023-10-20 11:17 UTC, Pranshu1902 commented
@sainak done

2023-10-25 07:59 UTC, Pranshu1902 commented
@vigneshhari please review and merge the PR

2023-12-07 18:42 UTC, merged