Made doctor role as static attribute
coronasafe/care pull request #1507
Opened 2023-08-03 11:21 UTC by Bhavik-ag

## Proposed Changes
- Doctor status and role to be stored as static attribute
- Add a `doctor` role type to the home facility doctor
- Add a `remote specialist` role type to the outside facility doctors
- Add `user_type` as role if not a doctor
- Add an empty string if not note is created before

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2023-08-03 12:38 UTC, sainak requested changes

2023-08-03 12:38 UTC, sainak commented on care/facility/models/patient.py
> +    created_by_local_user = models.CharField(max_length=25, default="")
Rename the field to `user_type`

2023-08-07 16:57 UTC, sainak approved these changes

2023-08-13 19:10 UTC, vigneshhari commented
@gigincg @aparnacoronasafe This change requires an ops review as well.

2023-08-15 15:50 UTC, rithviknishad reviewed
rebase your migrations after ops approval.

2023-08-24 14:26 UTC, sainak commented
@vigneshhari this pr is good to merge, we got ops approval

2023-08-24 16:31 UTC, vigneshhari approved these changes

2023-08-24 16:37 UTC, merged