adds titrated prescription
coronasafe/care pull request #1692
Opened 2023-10-30 12:17 UTC by GokulramGHV

## Proposed Changes

- Added titrated prescription

### Associated Issue

- coronasafe/care_fe#6432
- #1668

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2023-10-31 14:53 UTC, rithviknishad requested changes

2023-10-31 14:53 UTC, rithviknishad commented on care/facility/api/serializers/prescription.py
> +    last_administration = serializers.SerializerMethodField()
This can be a `MedicineAdministrationSerializer` itself right instead of a `SerializerMethodField`?

2023-10-31 14:53 UTC, rithviknishad commented on care/facility/api/serializers/prescription.py
> +                )
`base_dosage` is mandatory for all types of prescriptions right? Not just for titrated right?

2023-10-31 14:53 UTC, rithviknishad commented on care/facility/api/serializers/prescription.py
> +                )
Also, we should add required validation for max_dosage if it is PRN prescription right?

2023-10-31 14:53 UTC, rithviknishad commented on care/facility/api/serializers/prescription.py
> +            return LastAdministrationSerializer(last_administration).data
Any reason for a dedicated serializer to serialize last administration?

This can be a `MedicineAdministrationSerializer` itself right?

2023-10-31 14:53 UTC, rithviknishad commented on care/facility/api/viewsets/prescription.py
> +    # is_prn = filters.BooleanFilter()
```suggestion
```

2023-10-31 14:53 UTC, rithviknishad commented on care/templates/reports/patient_discharge_summary_pdf.html
Are we not showing columns for titrated dosages in the discharge summary?
We could show it as a separate table maybe?

2023-10-31 14:53 UTC, rithviknishad commented on care/facility/tests/test_medicine_administrations_api.py
Tests for titrated dosage administrations needed.

2023-10-31 14:53 UTC, rithviknishad commented on care/facility/tests/test_prescriptions_api.py
Tests for titrated medicine administrations and related validations needed.

2023-11-06 16:20 UTC, rithviknishad commented
@GokulramGHV ensure your pre-commit hook is working. fix the lint errors. Lint CI is failing.

2023-11-07 03:45 UTC, rithviknishad commented on care/facility/migrations/0393_rename_dosage_prescription_base_dosage_and_more.py
> +        Prescription.objects.filter(dosage_type="PRN").update(is_prn=True)
We will have titrated prescriptions classified as normal prescriptions if we reverse this migration. Does this seem fine @sainak ?

2023-11-07 03:48 UTC, rithviknishad approved these changes
Other than the discharge summary, everything LGTM. @GokulramGHV

2023-11-10 17:45 UTC, rithviknishad requested changes

2023-11-10 17:45 UTC, rithviknishad commented on care/facility/api/serializers/prescription.py
@GokulramGHV in the Prescription serializer, also pop `max_dosage` if not PRN and pop target dosage if not Titrated dosage. We shouldn't store these in the db even if the front-end accidentally passes it to the BE.

2023-11-15 04:21 UTC, rithviknishad requested changes

2023-11-15 04:21 UTC, rithviknishad commented on care/facility/api/serializers/prescription.py
> +            attrs.pop("dosage", None)
Is this correct? this would mean for all valid administrations, dosage would be popped, right (even for titrated prescription administrations)?

2023-11-15 04:22 UTC, rithviknishad commented
Also the tests are failing. could you rebase your migrations?

2023-11-16 10:32 UTC, rithviknishad approved these changes

2023-11-28 12:05 UTC, rithviknishad commented on care/facility/models/prescription.py
> +    dosage = models.CharField(max_length=100, blank=True, null=True)
Should we consider populating this with the `base_dosage` value from the prescription for non-titrated prescriptions?

```suggestion
    dosage = models.CharField(max_length=100)
```

2023-12-06 12:18 UTC, sainak requested changes

2023-12-06 12:18 UTC, sainak commented on care/facility/api/serializers/prescription.py
> +        elif self.context["prescription"].dosage_type != "TITRATED":
use enum to reference the dosage_type

example: `self.context["prescription"].dosage_type != PrescriptionDosageType.TITRATED`

2023-12-06 12:18 UTC, sainak commented on care/facility/api/serializers/prescription.py
> +            if attrs.get("dosage_type") == "TITRATED":
use enum to reference dosage_type

2023-12-07 10:46 UTC, sainak approved these changes

2023-12-07 10:49 UTC, sainak commented
@GokulramGHV when you are using TextChoices you don't need to access the value of the enum states, so you can use `PrescriptionDosageType.REGULAR` as a parameter directly

2023-12-08 08:13 UTC, rithviknishad requested changes
https://github.com/coronasafe/care/commit/46341e13cc4fb43b07b30bd6a41a343cebbac0d0 has bought support to validate dosage fields. That must be incorporated too to the new dosage fields

2023-12-08 08:13 UTC, rithviknishad commented on care/facility/models/prescription.py
> +    base_dosage = models.CharField(max_length=100, blank=True, null=True)
Add `dosage_validator` here

2023-12-08 08:13 UTC, rithviknishad commented on care/facility/models/prescription.py
> +    target_dosage = models.CharField(max_length=100, blank=True, null=True)
here too

2023-12-08 08:13 UTC, rithviknishad commented on care/facility/models/prescription.py
> +    dosage = models.CharField(max_length=100, blank=True, null=True)
here too

2023-12-09 12:18 UTC, rithviknishad approved these changes

2023-12-12 09:09 UTC, nihal467 commented
@GokulramGHV fix the test

2023-12-20 14:08 UTC, nihal467 commented
@GokulramGHV rebase it to the latest bro because I am unable to load dummy data.

2023-12-20 14:23 UTC, GokulramGHV commented
@nihal467 Can you check now?

2023-12-26 13:26 UTC, nihal467 commented
<img width="960" alt="image" src="https://github.com/coronasafe/care/assets/57055998/03f9eaff-5a97-468e-aa5a-32d78329a7a2">

@GokulramGHV iam unable to load the dummy data to your PR, tried with a new fresh database as well, something is wrong

2023-12-26 13:33 UTC, Ashesh3 commented
> <img alt="image" width="960" src="https://private-user-images.githubusercontent.com/57055998/292874526-03f9eaff-5a97-468e-aa5a-32d78329a7a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1OTc3OTMsIm5iZiI6MTcwMzU5NzQ5MywicGF0aCI6Ii81NzA1NTk5OC8yOTI4NzQ1MjYtMDNmOWVhZmYtNWE5Ny00NjhlLWFhNWEtMzJkNzgzMjlhN2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDEzMzEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwNzFiN2NlMWEzNzdjMTZhNDFkOTViYmRkNjAzMzk3Y2Q1YmJmZWE4MTMyOTllNDQ4YzJjMjQ1NzcxYTkyZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CNs6T16xFrNtNoeswZkhWVuFD-YIGE0B3ySwAv0aWKM">
> @GokulramGHV iam unable to load the dummy data to your PR, tried with a new fresh database as well, something is wrong
> 
> CC: @sainak

`django.core.exceptions.FieldDoesNotExist: Prescription has no field named 'dosage'`
Seems like the `dosage` was renamed to `base_dosage`. Update dummy data fixture `facility.json` accordingly.

2023-12-26 14:06 UTC, GokulramGHV commented
@Ashesh3 thanks, I'll update it

2023-12-26 14:26 UTC, GokulramGHV commented
@nihal467 Please check now

2023-12-27 13:15 UTC, nihal467 commented
LGTM

2023-12-27 14:39 UTC, khavinshankar approved these changes

2023-12-27 17:28 UTC, sainak approved these changes

2024-02-26 10:25 UTC, sainak approved these changes

2024-03-17 05:38 UTC, vigneshhari approved these changes

2024-03-17 05:38 UTC, merged