Rename `admission_date` to `encounter_date` and clean column
coronasafe/care pull request #1728
Opened 2023-11-27 07:57 UTC by rithviknishad

## Proposed Changes

- Rename `admission_date` to `encounter_date`
- Updated validations to allow `encounter_date` for all consultations
- ⚠️ **Custom migration**: set `encounter_date` to `null` for existing consultations that are not admission/domiciliary care

### Associated Issue

- https://github.com/coronasafe/care_fe/issues/6669
- https://github.com/coronasafe/care_fe/issues/6668

## Merge Checklist

- [x] Tests added/fixed
- [ ] Update docs in `/docs`
- [x] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2023-11-27 12:45 UTC, sainak requested changes
LGTM

2023-11-27 12:45 UTC, sainak commented on care/facility/models/patient_consultation.py
> +    encounter_date = models.DateTimeField(default=timezone.now)
We should index this field

2023-11-27 13:09 UTC, sainak approved these changes

2023-12-06 12:33 UTC, nihal467 commented
LGTM

2023-12-07 18:10 UTC, vigneshhari commented
Resolve Conflicts.

2023-12-20 16:25 UTC, vigneshhari approved these changes

2023-12-20 16:26 UTC, merged