`listAssetAvailability` queryset to send all related assets record status
coronasafe/care pull request #1794
Opened 2023-12-30 11:43 UTC by Pranshu1902

## Proposed Changes

Modify the `AssetAvailabilityViewSet` query set to send the asset uptime status of all assets related to the user

### Associated Issue
Partially Fixes [#6819](https://github.com/coronasafe/care_fe/issues/6819)

### Architecture changes

- Remove this section if not used

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-01-04 07:28 UTC, rithviknishad requested changes
Changes required as per https://github.com/coronasafe/care_fe/pull/6952#pullrequestreview-1799610356

2024-01-18 13:07 UTC, Pranshu1902 commented
@sainak could you review these changes

2024-01-18 13:57 UTC, sainak requested changes

2024-01-18 13:57 UTC, sainak commented on care/facility/api/viewsets/asset.py
> +            setattr(asset, "down", bool(asset.latest_status))
```suggestion
        last_status=Subquery(
		        AssetAvailabilityRecord.objects.filter(asset=OuterRef("pk"))
		        .order_by("-created_date")
		        .values("status")[:1]
    			)
        )
```

2024-01-18 13:57 UTC, sainak commented on care/facility/api/viewsets/asset.py
> +    def filter_queryset(self, queryset: QuerySet) -> QuerySet:
you could do this in the get_queryset, that way you will be able to use this to filter assets

2024-01-18 13:57 UTC, sainak commented
add test cases

2024-01-22 15:18 UTC, rithviknishad reviewed
This would mean that the "AssetSerializer" can now only be used by "AssetViewset" since the field is annotated in the `get_queryset`.

If we were to use the "AssetSerializer" elsewhere, wouldn't this cause issues since we would not/need not be annotating it there.

@sainak is this correct?

2024-01-22 15:42 UTC, rithviknishad approved these changes

2024-01-22 16:16 UTC, sainak approved these changes

2024-01-22 20:43 UTC, nihal467 commented
LGTM

2024-01-28 06:45 UTC, Pranshu1902 commented
@vigneshhari could you review this PR

2024-02-10 09:31 UTC, vigneshhari approved these changes

2024-02-10 09:32 UTC, vigneshhari commented
It might be better to cache this data in the main record to make the query simpler.

2024-02-10 09:32 UTC, merged