Add nurse user type
coronasafe/care pull request #1819
Opened 2024-01-10 14:30 UTC by sainak

This pull request adds a new user type called "Nurse" and migrates the existing staff users to the nurse role. It also includes updates to permissions checks.

2024-01-10 19:07 UTC, rithviknishad approved these changes

2024-01-11 02:29 UTC, Ashesh3 approved these changes

2024-01-11 08:05 UTC, vigneshhari requested changes

2024-01-11 08:05 UTC, vigneshhari commented on care/facility/api/viewsets/file_upload.py
> +        if self.request.user.user_type in (
Maybe switch this to a permission check, kinda misplaced in the query set. A new Permission Check would be great.

2024-01-11 08:41 UTC, sainak reviewed
move permission checks out of geet_queryset

2024-01-11 15:49 UTC, vigneshhari approved these changes
Approved without review.

2024-01-11 15:49 UTC, merged