ABDM M3
coronasafe/care pull request #1829
Opened 2024-01-17 04:12 UTC by khavinshankar

Added milestone 3 for ABDM (https://sandbox.abdm.gov.in/abdm-docs/Milestone_three)

2024-01-17 10:45 UTC, sainak requested changes

2024-01-20 07:53 UTC, khavinshankar commented on care/abdm/models/abha_number.py
> +    health_id = models.TextField(null=True, blank=True, unique=True)
@sainak Ideally, there shouldn't be any duplicates as this is unique for each person (patient). Can you run a quick query to check if there are any duplicates in prod?

2024-01-22 08:59 UTC, Ashesh3 approved these changes

2024-01-23 14:15 UTC, rithviknishad approved these changes

2024-01-24 05:13 UTC, sainak approved these changes

2024-01-24 05:14 UTC, sainak commented on care/abdm/models/abha_number.py
> +    health_id = models.TextField(null=True, blank=True, unique=True)
sure

2024-04-12 11:51 UTC, sainak commented on care/abdm/utils/api_call.py
> +        }
```suggestion
        auth_header = Request("").auth_header()
        
        if not auth_header:
            return None

        headers = {
            "Content-Type": "application/json",
            **auth_header
        }
```
Request("").auth_header() seems to be checking the cache already, so we can remove the duplicate logic

2024-04-12 11:53 UTC, sainak commented on care/abdm/service/gateway.py
> +                "dataPushUrl": f"https://{settings.BACKEND_DOMAIN}"
```suggestion
                "dataPushUrl": settings.BACKEND_DOMAIN}
```
this value already has the https prefix

2024-04-12 14:33 UTC, rithviknishad approved these changes

2024-04-12 16:38 UTC, Ashesh3 approved these changes

2024-04-13 04:25 UTC, gigincg commented
@khavinshankar Can you make a PR on the docs Repo for ABDM M3 and placeholders for M1 & M2

Also, there seems to be a couple of conflicts, can you get these cleared

2024-05-13 14:07 UTC, merged