added user type check before creating new asset
coronasafe/care pull request #1868
Opened 2024-02-01 15:33 UTC by kshitijv256

## Proposed Changes

- Added user type check before creating new asset

### Associated Issue

- https://github.com/coronasafe/care_fe/issues/7081

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-02-22 17:23 UTC, sainak requested changes
use dry permissions for this validation
https://github.com/dbkaplan/dry-rest-permissions

2024-02-23 10:23 UTC, rithviknishad approved these changes

2024-02-23 10:23 UTC, rithviknishad approved these changes

2024-03-01 12:21 UTC, sainak commented on care/facility/api/serializers/asset.py
> +        user = self.context["request"].user
where is this being used?

2024-03-01 12:21 UTC, sainak commented
add test cases

2024-03-01 15:55 UTC, kshitijv256 commented
> add test cases

@sainak 
I am unable to create a test case as different user type is needed, can you give some idea how

2024-03-01 16:21 UTC, rithviknishad commented
@kshitijv256 example: https://github.com/coronasafe/care/pull/1866/files#diff-6e69c1bec5735c00ad8c3637de1e270b87399c4a6958c4496a9d145e3025d333R90

2024-05-12 11:36 UTC, closed without merging