Track Occupation of Patient
coronasafe/care pull request #1901
Opened 2024-02-20 13:34 UTC by konavivekramakrishna

## Proposed Changes

- change occupation choices
- head_of_household can be null

### Associated Issue

- https://github.com/coronasafe/care_fe/issues/6945

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-02-20 13:35 UTC, konavivekramakrishna commented
@sainak 

could you please review it

2024-02-20 13:37 UTC, sainak approved these changes

2024-02-26 11:19 UTC, rithviknishad approved these changes

2024-03-04 13:30 UTC, vigneshhari requested changes

2024-03-04 13:30 UTC, vigneshhari commented on care/facility/models/patient.py
> +        BUSINESSMAN = 2
Changing labels without remapping the values would corrupt the data right?

2024-03-04 13:32 UTC, vigneshhari approved these changes

2024-03-04 13:34 UTC, vigneshhari commented on care/facility/api/serializers/patient.py
> +                        setattr(patient.meta_info, key, value)
possibly confirm that we are not allowing to edit internal fields in this manner. ( eg, id, uuid, FK's and so on.. )

2024-03-04 13:34 UTC, merged