Add validation checks in ResourceRequestSerializer
coronasafe/care pull request #1928
Opened 2024-02-28 21:37 UTC by rash-27

## Proposed Changes

- Add validation checks in ResourceRequestSerializer using ExternalIdSerializerField

### Associated Issue

- #1914 

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-02-29 04:20 UTC, sainak requested changes
- similar checks are present in the update method, remove them as well
- add test cases

2024-03-02 11:51 UTC, sainak approved these changes

2024-03-02 13:30 UTC, Ashesh3 approved these changes

2024-03-02 17:17 UTC, sainak commented
@rash-27 fix lint issues https://github.com/coronasafe/care/blob/master/CONTRIBUTING.md

2024-03-02 22:14 UTC, rash-27 commented
@sainak fixed lint errors but was unable to push (encountering this error), and even the pulling not worked 
![Screenshot 2024-03-03 034210](https://github.com/coronasafe/care/assets/146672184/5768f84d-1204-4803-a17a-3c3c525a125e)

2024-03-11 10:39 UTC, sainak approved these changes

2024-03-11 10:39 UTC, sainak approved these changes

2024-03-11 11:24 UTC, rithviknishad approved these changes

2024-03-17 05:43 UTC, vigneshhari approved these changes

2024-03-17 05:43 UTC, merged