Fix:Migration of new facility types
coronasafe/care pull request #1932
Opened 2024-02-29 13:08 UTC by SinghYuvraj0506

## Proposed Changes

1. Updated the Facility types in Facility.py model 
2. Created a Migration for the updated model.

### Associated Issue
https://github.com/coronasafe/care/issues/1931

<img width="967" alt="image" src="https://github.com/coronasafe/care/assets/98007961/c4ea23a8-2aff-45b6-b77b-4ce3fed06765">

## Merge Checklist

- [X] Linting Complete
- [X] Ran the Docker test

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-03-01 04:58 UTC, sainak requested changes

2024-03-01 04:58 UTC, sainak commented on care/facility/migrations/0415_alter_facility_facility_type_and_more.py
Custom migrations required to migrate deprecated types to new types

2024-03-02 05:44 UTC, closed without merging

2024-03-02 07:07 UTC, SinghYuvraj0506 commented on care/facility/migrations/0415_alter_facility_facility_type_and_more.py
@sainak created a new pull request https://github.com/coronasafe/care/pull/1936

2024-03-04 05:39 UTC, Ashesh3 commented
Closed in favor of https://github.com/coronasafe/care/pull/1936