Replace age field with DOB in users model
coronasafe/care pull request #1935
Opened 2024-03-01 23:27 UTC by rash-27

## Proposed Changes

- Replace the age field with the date of birth in Users model 

### Associated Issue

-  #7281 in the frontend requires this change 

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-03-02 04:30 UTC, rithviknishad requested changes
Missing custom migration to migrate existing users' age to DOB

2024-03-02 07:35 UTC, rash-27 commented
Ok I'll update it

2024-03-02 12:00 UTC, sainak requested changes
update dummy data

2024-03-02 12:00 UTC, sainak commented on care/users/api/serializers/user.py
> +            raise serializers.ValidationError("Enter a valid date of birth.")
```suggestion
        if value and now().year - value.year < 16:
            raise serializers.ValidationError("Age must be greater than 15 years")
```

2024-03-02 12:02 UTC, sainak commented on care/users/models.py
> +    date_of_birth = models.DateField(null=True, blank=True)
make this non nullable after migration

2024-03-02 12:03 UTC, sainak commented on care/users/api/serializers/user.py
> +    date_of_birth = serializers.DateField(required=False)
```suggestion
    date_of_birth = serializers.DateField(required=True)
```

2024-03-02 12:03 UTC, sainak commented on care/users/api/serializers/user.py
> +    date_of_birth = serializers.DateField(required=False)
```suggestion
    date_of_birth = serializers.DateField(required=True)
```

2024-03-04 06:58 UTC, rithviknishad requested changes

2024-03-04 06:58 UTC, rithviknishad commented on care/users/migrations/0015_age_to_dateofbirth.py
> +        migrations.RunPython(age_to_date_of_birth, migrations.RunPython.noop),
Needs reverse_code to reverse DOB to age

2024-03-04 08:43 UTC, rithviknishad approved these changes

2024-03-11 10:56 UTC, sainak approved these changes

2024-03-18 09:26 UTC, vigneshhari commented
Does it make sense to use Jan 1 in the migrations, a random DOB seems wrong to me.

2024-03-18 09:44 UTC, rash-27 commented
@vigneshhari here in the database we store only the age previously in Users model, 
1. Choosing a random value of date of birth is  to save the age of the user as we eliminate the age field after migration 
2. choosing only jan 1 as random dob is because , we can accurately calculate the age if needed , if we choose another date , our age calculated will get inconsistent if the actual date of birth is before the chosen date of birth
Please correct me , if I am wrong

2024-03-20 09:28 UTC, vigneshhari commented
okays, we can merge after the lint and tests pass

2024-03-24 13:56 UTC, rash-27 commented
@vigneshhari I have modified the tests and they are passing  
![image](https://github.com/coronasafe/care/assets/146672184/7416c2f6-2d61-4431-abde-52b83ca6aa9e)

2024-03-24 16:29 UTC, vigneshhari approved these changes

2024-03-24 16:29 UTC, merged