Add django filter for patient review missed
coronasafe/care pull request #1938
Opened 2024-03-02 20:30 UTC by jainvedant392

## Proposed Changes

- Added a custom filter "review_missed", checking whether "review_time" is greater than present data or not. 

### Associated Issue

- [care_fe issue #6745](https://github.com/coronasafe/care_fe/issues/6745)

## Merge Checklist

- [x] Tests added/fixed
- [x] Update docs in `/docs`
- [x] Linting Complete
- [x] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-03-04 07:06 UTC, rithviknishad requested changes
Need tests

2024-03-04 09:01 UTC, jainvedant392 commented
> Need tests

@rithviknishad , Do I have to do them?

2024-03-11 10:41 UTC, sainak commented
> > Need tests
> 
> @rithviknishad , Do I have to do them?

yes

2024-03-13 05:40 UTC, jainvedant392 commented
@sainak Could you please guide me a little on how to write tests for the changes I have made?

2024-03-23 08:29 UTC, jainvedant392 commented
Hey @sainak, I have added test for the review missed filter, could you please review them?

2024-03-23 08:31 UTC, jainvedant392 commented
In the test, I am checking inside a loop whether every patient, in the response returned, satisfies the condition for a missed review

2024-03-30 08:38 UTC, sainak commented on care/facility/tests/test_patient_api.py
> +        self.client.force_authenticate(user=self.user)
```suggestion
```

2024-03-30 09:02 UTC, sainak approved these changes

2024-04-04 08:38 UTC, Ashesh3 approved these changes

2024-04-09 11:07 UTC, vigneshhari approved these changes

2024-04-09 11:07 UTC, merged