Add created_by and updated_by fields to base model
coronasafe/care pull request #1940
Opened 2024-03-04 20:16 UTC by AnkurPrabhu

## Proposed Changes

- Added 2 new fields in base model created_by and updated_by 
- created migrations for the same
- updated the create and update function of viewsets to add values to created_by and updated_by fields

### Associated Issue
- Link to issue #1697  

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-03-05 12:59 UTC, sainak commented
initial changes look good, you can proceed with adding created_by updated_by to other models as well

2024-03-05 20:29 UTC, AnkurPrabhu commented
> initial changes look good, you can proceed with adding created_by updated_by to other models as well

Hey i made the changes at all the places but i realised that perform_update does not need to update created_by field while saving so i have done all the changes will test it locally and then push it for review

2024-03-06 20:50 UTC, AnkurPrabhu commented
@sainak i have updated the pr, please take a look and let me know if there are any changes i have tested for some of the models it works fine for me

2024-03-07 16:18 UTC, sainak commented
> @sainak i have updated the pr, please take a look and let me know if there are any changes i have tested for some of the models it works fine for me

hey @AnkurPrabhu, thanks for these changes, currently focused on some high-priority issues, I'll surely review this pr once I'm done with those

2024-03-11 10:54 UTC, sainak requested changes

2024-03-11 14:55 UTC, AnkurPrabhu commented on care/facility/api/viewsets/patient_otp.py
> +        serializer.save(updated_by=self.request.user)
so remove it form here ?

2024-03-11 14:56 UTC, AnkurPrabhu commented on care/facility/api/viewsets/mixins/access.py
cool wil do

2024-03-11 14:56 UTC, AnkurPrabhu commented
@sainak  these are the only changes ?

2024-03-16 08:09 UTC, AnkurPrabhu commented
@sainak  any other changes required for this or only these 2

2024-03-18 10:54 UTC, sainak commented
> @sainak any other changes required for this or only these 2

yes
make the changes and get it tested by @nihal467

2024-03-19 19:58 UTC, AnkurPrabhu commented
@sainak have resolved your comments. @nihal467 please take a look, I have tested it for some endpoints in my local

2024-03-20 06:38 UTC, sainak commented on care/facility/api/viewsets/mixins/access.py
@AnkurPrabhu this was not resolved in the last commit

2024-03-20 19:17 UTC, AnkurPrabhu commented
@nihal467  just a reminder to take a look, please take a look when you are available

2024-03-23 09:05 UTC, AnkurPrabhu commented on care/facility/api/viewsets/mixins/access.py
i have added perform update method right in commit https://github.com/coronasafe/care/pull/1940/commits/8e63db6df36b8a036ec99ac1f3483d83eeafb8e1

2024-03-26 15:57 UTC, AnkurPrabhu commented
@sainak @nihal467  there were some merge conflicts due to recent db changes made by @rithviknishad I have now rebased it but can we get this tested ?
as the changes are in a lot of models and can conflict frequently with other branches

2024-04-08 22:46 UTC, nihal467 commented
@AnkurPrabhu 
![image](https://github.com/coronasafe/care/assets/57055998/ddc9f18e-9f9e-4157-adf9-7784ed547c86)

the backend is not loading properly in docker, just check your PR is working properly , there are migration missing in it

2024-04-09 14:05 UTC, AnkurPrabhu commented
> @AnkurPrabhu ![image](https://private-user-images.githubusercontent.com/57055998/320667486-ddc9f18e-9f9e-4157-adf9-7784ed547c86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzE3NzEsIm5iZiI6MTcxMjY3MTQ3MSwicGF0aCI6Ii81NzA1NTk5OC8zMjA2Njc0ODYtZGRjOWYxOGUtOWY5ZS00MTU3LWFkZjktNzc4NGVkNTQ3Yzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE0MDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZGMxNjczZjU2YWM0ZjMwN2NjNDk5NDkwYWQ1ZWE4ZGI5NzU0OTY1ZDhiOTg2YjQ2NDRhNDg4OWMyNDRiZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.93IBcYzzgi-R8Oep83bsgcTGLH73xUv09zQnrf0goAE)
> 
> the backend is not loading properly in docker, just check your PR is working properly , there are migration missing in it


was working fine for me will take a look

2024-04-10 14:30 UTC, AnkurPrabhu commented
@nihal467 there was a pr which was related to db change which was conflicting with my change deleted those migrations and created new ones.

2024-04-10 18:26 UTC, AnkurPrabhu commented
@sainak @nihal467 the docker for me now shows update_by field already present is table ambulance but its not.
also it says "facility_ambulance" so how are they related i was not able to find this, the relation seems like the issue here 
 
<img width="1491" alt="Screenshot 2024-04-10 at 11 45 55 PM" src="https://github.com/coronasafe/care/assets/85862184/a54bbc82-e20a-4558-82ff-f9da76c13ca9">

2024-04-16 22:36 UTC, nihal467 commented
![image](https://github.com/coronasafe/care/assets/57055998/d249ac02-f615-405e-a358-2c021fc2563a)

it's still throwing error, fix it

2024-05-12 11:37 UTC, closed without merging