[BUG] fix Location/ Bed Management issue ( District Lab Admin Account)
coronasafe/care pull request #1959
Opened 2024-03-11 16:25 UTC by AnkurPrabhu

## Proposed Changes

- Brief of changes made.
   the issue here was mainly permission related 
   District Lab Admin had read access for facility but not object read access (refer FacilityPermissionMixin)
   same for asset_location while actually managing beds it uses (refer FacilityRelatedPermissionMixin) 

### Associated Issue

- Link to issue here : [issue](https://github.com/coronasafe/care_fe/issues/7102)

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [x] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-03-11 16:26 UTC, AnkurPrabhu commented
@rithviknishad  @sainak pls take a look works fine for me

2024-03-11 16:39 UTC, rithviknishad requested changes
A state lab admin and greater user would have access to facilities belonging to the user's state and not user's district

2024-03-11 16:40 UTC, rithviknishad commented
Also, need tests

2024-03-11 16:59 UTC, AnkurPrabhu commented
> A state lab admin and greater user would have access to facilities belonging to the user's state and not user's district

@rithviknishad i did not understand this comment what change is needed we dont allow object read for district lab admin ?

i added it to district lab admin as in FacilityQSPermissions we allow DistrictLabAdmin to view it

2024-03-11 17:02 UTC, rithviknishad commented
FacilityQSPermissions also has a case for state lab admin and greater user:

<img width="1064" alt="image" src="https://github.com/coronasafe/care/assets/25143503/a26e094b-cc00-4cda-8d9a-f5eecdf126a4">

2024-03-11 17:04 UTC, AnkurPrabhu commented
okay is this what ur saying 
i have to add 
   hasattr(self, "district")
   and 
      hasattr(self, "state")
    instead of simply. adding request.user.user_type >= User.TYPE_VALUE_MAP["DistrictLabAdmin"] ?

2024-03-16 12:58 UTC, AnkurPrabhu commented
hey i just noticed that for model AssetLocation we dont have a field named state thats why its failing for assetlocation where as for facility we have state so this fixed the facility permission issue part but shows the error while managing beds 
should i add the state field  ? 
@rithviknishad

2024-03-17 06:04 UTC, rithviknishad commented
We don't need to add a state field as it'd no longer be having a single source of truth.

A facility belongs to a state and Asset Location belongs to a facility. Bed belongs to an Asset Location.

2024-03-19 17:15 UTC, AnkurPrabhu commented
@rithviknishad i have added tests and also did the same for state lab admin looks good to me let me know if any changes are required

2024-03-20 06:46 UTC, rithviknishad approved these changes

2024-03-20 07:06 UTC, sainak approved these changes

2024-03-21 14:42 UTC, Ashesh3 approved these changes

2024-03-21 19:24 UTC, AnkurPrabhu commented
@khavinshankar  pls take a look

2024-03-24 16:30 UTC, vigneshhari approved these changes

2024-03-24 16:30 UTC, merged