Add routes and authentcation to allow asset config fetching by middlewares
coronasafe/care pull request #2000
Opened 2024-03-21 09:49 UTC by sainak

## Proposed Changes

- add middleware level auth
- cache middleware openid keys
- cleanup middleware auth
- add route to fetch asset configs for middlewares
- allow middleware asset to access  related assetbeds

### Associated Issue

- required for https://github.com/coronasafe/teleicu_middleware/issues/118

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-03-28 05:34 UTC, Ashesh3 approved these changes

2024-03-28 05:35 UTC, khavinshankar approved these changes

2024-03-28 05:39 UTC, rithviknishad approved these changes

2024-04-09 11:05 UTC, vigneshhari requested changes

2024-04-09 11:05 UTC, vigneshhari commented on care/facility/api/serializers/asset.py
> +                    .annotate(
Refactor

2024-04-09 11:05 UTC, vigneshhari commented on care/facility/api/serializers/asset.py
> +            response = push_config_to_middleware(
Move to background task

2024-04-09 11:05 UTC, vigneshhari commented on care/facility/api/viewsets/asset.py
> +                    NullIf(
See if you can use the or statement here

2024-04-09 11:05 UTC, vigneshhari commented on care/facility/migrations/0426_dailyround_is_parsed_by_ocr_and_more.py
> +        migrations.AddIndex(
Remove Index

2024-04-10 10:48 UTC, sainak commented on care/facility/api/serializers/asset.py
> +                    .annotate(
Converting this to or was breaking the validation

2024-04-10 10:49 UTC, sainak commented on care/facility/api/viewsets/asset.py
> +                    NullIf(
Converting this to or was returning assets from other hostnames as well

2024-04-14 18:45 UTC, merged