adding configurable backend
coronasafe/care pull request #2024
Opened 2024-03-27 19:21 UTC by AnkurPrabhu

## Proposed Changes

- Have used django-sms and make a custom backend for our existing sns

### Associated Issue

-  #664 

## Merge Checklist

- [ x] Tests added/fixed
- [ ] Update docs in `/docs`
- [ x] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-03-27 19:22 UTC, AnkurPrabhu commented
@sainak ptal, shoud i add tests for other places as well ?

2024-03-30 08:24 UTC, sainak requested changes

2024-03-30 08:24 UTC, sainak commented on Pipfile
> +django-sms = "*"
pin to a specific version

2024-03-30 08:24 UTC, sainak commented on care/utils/sms/sendSMS.py
> +        client = boto3.client(
initialize the client in `__init__()`

2024-03-30 08:24 UTC, sainak commented on care/utils/sms/sendSMS.py
> +                client.publish(PhoneNumber=phone_number, Message=message_body)
handle exceptions

2024-03-30 08:24 UTC, sainak commented on config/settings/local.py
> +SMS_BACKEND = "care.utils.sms.sendSMS.CustomSMSBackendSNS"
set `SMS_BACKEND = "care.utils.sms.sendSMS.CustomSMSBackendSNS"` in base settings
and for local and test use console backend

2024-03-30 08:26 UTC, sainak commented
@vigneshhari though the django-sms provides a standard wrapper for sms, the backend themselves have different names for settings, and some backends require client sdks to be installed
also I just noticed that django-sms has a 3BSD license

2024-04-05 20:37 UTC, AnkurPrabhu commented
@sainak let me know if the changes made look good to you

2024-04-08 06:14 UTC, sainak commented
Hey @AnkurPrabhu thanks for these changes, but we are planning to move the sms backends to a plugin system, once the plugin architecture becomes stable, we will create our own implementation for the sms

cc: @vigneshhari

2024-05-12 11:38 UTC, closed without merging