upgrade user skills
coronasafe/care pull request #2096
Opened 2024-04-16 22:16 UTC by rash-27

## Proposed Changes

- Updated the skills of users list

### Associated Issue

- fixes issue https://github.com/coronasafe/care_fe/issues/7616
## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-04-18 04:48 UTC, sainak requested changes
@rash-27 you also need to create a custom migration that will add the newly added skills to db if not present, add a condition to skip if the skill table is empty (this would be the case with new instance, so users are expected to load the skill using the load skill command)

2024-04-18 05:02 UTC, rash-27 commented
Ok will add it

2024-04-18 05:59 UTC, rash-27 commented
@sainak is this the required migration , or am I missing something?

2024-04-18 10:56 UTC, sainak approved these changes

2024-04-18 10:59 UTC, rithviknishad approved these changes

2024-04-22 18:52 UTC, vigneshhari approved these changes

2024-04-22 18:52 UTC, merged