added tests for beds endpoints
coronasafe/care pull request #2104
Opened 2024-04-20 17:01 UTC by DraKen0009

## Proposed Changes

- Created Testcases for Bed Enpoint

### Associated Issue
#2103 

## Merge Checklist

- [x] Tests added/fixed
- [x] Linting Complete

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-05-14 15:13 UTC, khavinshankar requested changes
LGTM, just some minor improvements

2024-05-14 15:13 UTC, khavinshankar commented on care/facility/tests/test_bed_api.py
> +        self.assertEqual(response.data["results"][0]["name"], self.bed2.name)
let's also check the count here

2024-05-14 15:13 UTC, khavinshankar commented on care/facility/tests/test_bed_api.py
> +        self.assertEqual(response.data["results"][0]["name"], self.bed3.name)
let's also check the count here

2024-05-14 15:20 UTC, rithviknishad requested changes
LGTM, just some minor nitpicks to follow consistent patterns

2024-05-14 15:20 UTC, rithviknishad commented on care/facility/tests/test_bed_api.py
> +        response = self.client.get("/api/v1/bed/?bed_type=ISOLATION")
```suggestion
        response = self.client.get("/api/v1/bed/", {"bed_type": "ISOLATION"})
```

2024-05-14 15:20 UTC, rithviknishad commented on care/facility/tests/test_bed_api.py
> +        )
```suggestion
        response = self.client.get(
            f"/api/v1/bed/",
            { "facility": self.facility2.external_id },
        )
```

2024-05-14 15:20 UTC, rithviknishad commented on care/facility/tests/test_bed_api.py
> +        )
```suggestion
        response = self.client.get(
            "/api/v1/bed/",
            { "location": self.asset_location2.external_id },
        )
```

2024-05-14 15:38 UTC, gigincg commented
@DraKen0009 Can you make the changes?

2024-05-14 15:41 UTC, DraKen0009 commented
Yep. I'll update the PR by tonight or tomorrow afternoon.

2024-05-15 10:56 UTC, DraKen0009 commented
@rithviknishad  updated the PR. Can you please run the workflows once

2024-05-20 15:44 UTC, sainak commented on care/facility/tests/test_bed_api.py
> -            response = self.client.get("/api/v1/bed/")
@DraKen0009 can you revert this deletion, this was a good addition

2024-05-20 15:44 UTC, sainak commented on care/facility/tests/test_bed_api.py
> +            name="bed3", location=cls.asset_location2, facility=cls.facility2
moving this to setUpTestData, will create the objects only once, this could cause issues if you expect the objects to not change

2024-06-07 08:13 UTC, DraKen0009 commented
@sainak Fixed the conflicts, please check once

2024-06-07 14:06 UTC, skks1212 requested changes
@DraKen0009 tests are failing, please check

2024-06-07 14:14 UTC, DraKen0009 commented
@skks1212  fixed it.  Can you please run the workflows again.

2024-06-07 17:18 UTC, skks1212 approved these changes
LGTM, make sure to resolve all open conversations

2024-07-10 10:19 UTC, sainak approved these changes

2024-07-11 03:48 UTC, rithviknishad approved these changes

2024-07-12 14:44 UTC, vigneshhari approved these changes

2024-07-12 14:44 UTC, merged