Added discharge patient filters
coronasafe/care pull request #2124
Opened 2024-04-30 12:27 UTC by skks1212

## Proposed Changes

- Adds new advance filters for discharged patients.

### Associated Issue

- https://github.com/coronasafe/care_fe/issues/7737

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-05-03 13:41 UTC, rithviknishad requested changes

2024-05-03 13:41 UTC, rithviknishad commented on care/facility/api/viewsets/patient.py
> +    age_max = filters.NumberFilter(field_name="age", lookup_expr="lte")
Does the `age` filters work? You'll need to annotate the QuerySet with age and in Discharged Patient Viewset's Queryset it is not annotated.

2024-05-13 12:26 UTC, aparnacoronasafe commented
@skks1212 Will this be ready for production in next release? next monday?

2024-05-13 12:28 UTC, skks1212 commented
@aparnacoronasafe will try my best to get it reviewed and merged by then

2024-05-13 13:33 UTC, rithviknishad approved these changes

2024-05-13 18:20 UTC, sainak approved these changes

2024-05-14 16:13 UTC, vigneshhari commented
@sainak create a ticket to abstract repeated code. We can merge this in for now.

2024-05-14 16:13 UTC, merged

2024-05-14 21:01 UTC, sainak commented
> @sainak create a ticket to abstract repeated code. We can merge this in for now.

tracked in #2165