Prescriptions and MAR: Disallow users to perform edits on discharged encounters
coronasafe/care pull request #2133
Opened 2024-05-07 11:55 UTC by rithviknishad

## Proposed Changes

- Disallow actions to Prescription and Medicine Administration Records for discharged encounters.
- Merge prescription related tests to a single file and have dedicated test file for medicine administrations

### Associated Issue

- [x] Fixes https://github.com/coronasafe/care_fe/issues/7755
- [x] Fixes #2105

## Merge Checklist

- [x] Tests added/fixed
- [x] Linting Complete

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-05-13 05:13 UTC, rithviknishad commented
Waiting for confirmation regd. whether all remote users needs to be restricted or just remote nurses.

2024-05-13 05:34 UTC, rithviknishad commented
Confirmed. Doctors and Nurses of home facility only must be able to edit consultation related data. Other than doctor notes.

2024-05-13 08:39 UTC, sainak approved these changes

2024-05-14 05:02 UTC, skks1212 approved these changes

2024-05-21 08:33 UTC, nihal467 requested changes
- admin should be able to edit it irrespective of home facility privileges
- non-home facility staff is able to create medicine. block that as well in frontend as well backend

2024-06-04 18:10 UTC, nihal467 commented
@rithviknishad any update on this, is it good for review

2024-07-09 10:37 UTC, sainak approved these changes

2024-07-12 14:48 UTC, vigneshhari requested changes

2024-07-12 14:48 UTC, vigneshhari commented on care/facility/api/viewsets/prescription.py
> +        if self.get_consultation_obj().discharge_date:
This needs to be added in discontinue api as well

2024-08-05 01:59 UTC, gigincg commented
@rithviknishad Waiting for your changes

2024-08-23 03:18 UTC, sainak approved these changes

2024-09-22 17:12 UTC, vigneshhari approved these changes

2024-09-22 17:12 UTC, merged