Fix op number constraint for readmitted patients
coronasafe/care pull request #2147
Opened 2024-05-12 18:07 UTC by skks1212

## Proposed Changes

- Fixes https://github.com/coronasafe/care_fe/issues/7751

## Merge Checklist

- [x] Tests added/fixed
- [x] Update docs in `/docs`
- [x] Linting Complete
- [x] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-05-20 15:49 UTC, sainak requested changes

2024-05-20 15:49 UTC, sainak commented on care/facility/models/patient_consultation.py
> +                & models.Q(new_discharge_reason__isnull=False),
this wont work for more than 2 readmissions in the same facility,

2024-05-21 06:58 UTC, sainak commented
@skks1212 add test for the cases mentioned in the issue

2024-05-21 07:46 UTC, nihal467 commented
**Test Case** Status : In-progress 

- [ ] Same IP number for re-admitted patient within the facility { It should throw error }
- [ ] Same OP number for re-admitted patient within the facility
- [ ] OP number is unique for different patient within the facility
- [ ] OP number can be modified to match previous consultation OP number


**Bug** 
![image](https://github.com/coronasafe/care/assets/57055998/5a1f3f0b-c747-4787-99e2-634e3f910916)

- [ ] When we re-admit same patient to the same facility with same IP number , it is throw "something went wrong" error, reuse the existing error shown for unique IP number

2024-05-21 10:52 UTC, skks1212 commented
PR was incomplete, forgot to label as wip 😅. Fixing now

2024-05-21 13:26 UTC, nihal467 commented
@skks1212 the PR is still having bugs, I can create multiple consultation with same IP number for a single patient within a facility

2024-05-28 02:36 UTC, nihal467 commented
As per the issue , we are removing Data validation on the OP No. field.

2024-05-28 02:36 UTC, nihal467 commented
LGTM

2024-05-28 02:37 UTC, nihal467 approved these changes

2024-05-28 06:50 UTC, nihal467 reviewed
when a patient is discharged, and we reuse the same IP for next patient, it is being accept

Note: When a patient is live, and we try to reuse the IP for a new patient, this error is thrown properly

2024-05-28 06:51 UTC, sainak reviewed
test case required

2024-06-04 17:14 UTC, nihal467 commented
LGTM

2024-06-05 01:19 UTC, rithviknishad approved these changes

2024-06-05 02:43 UTC, khavinshankar approved these changes

2024-06-05 06:05 UTC, sainak approved these changes

2024-06-05 17:39 UTC, vigneshhari approved these changes

2024-06-05 17:40 UTC, vigneshhari commented
I still think we need a unique validator across patients, as in two live patients cannot have the same IP/OP number

2024-06-05 17:40 UTC, merged