Convert ABDM into Plug - Part 1/2
coronasafe/care pull request #2161
Opened 2024-05-14 10:20 UTC by khavinshankar

This pull request represents the first phase of converting the ABDM system into a plug. The primary focus of this PR is to refactor the relationship between the ABHA number and the patient model, alongside improvements to signal handling and routing. Detailed changes include:

- **Model Relationship Reversal:** Changed the relationship dynamics by moving the abha_number field from the patient model to the abha_number model. This involves making patient a field within the abha_number model to better align with our new architecture.

- **Signal Creation for Care Context:** Implemented a new signal that triggers the creation of a care context whenever a consultation is saved. This enhances the functionality and integration of care context within our system.

- **ABHA Number API Enhancements:** Introduced a new abha_number viewset, serializer, and routes. These additions are designed to streamline the handling and accessibility of ABHA numbers within our system.

This PR lays the groundwork for the subsequent phase, which will further integrate and optimize the ABDM plug system.

2024-05-14 19:41 UTC, sainak commented on care/abdm/api/viewsets/healthid.py
> +        if hasattr(patient, "abha_number") is False or patient.abha_number is None:
```suggestion
        if getattr(patient, "abha_number", None) is None:
```

2024-05-14 19:41 UTC, sainak commented on care/abdm/api/viewsets/healthid.py
> +        ):
```suggestion
        if getattr(consultation.patient, "abha_number", None) is None:
```

2024-05-14 19:41 UTC, sainak commented on care/abdm/api/viewsets/healthid.py
> +        if hasattr(patient, "abha_number") is False or patient.abha_number is None:
```suggestion
        if getattr(patient, "abha_number", None) is None:
```

2024-05-14 19:41 UTC, sainak commented on care/abdm/migrations/0013_abhanumber_patient.py
> +            abha_number.save()
use bulk update

2024-05-14 19:41 UTC, sainak commented on care/abdm/receivers/consultation.py
> +    if created and hasattr(patient, "abha_number") and patient.abha_number is not None:
```suggestion
    if created and getattr(patient, "abha_number", None) is not None:
```

2024-05-20 04:53 UTC, rithviknishad approved these changes

2024-05-20 14:09 UTC, sainak approved these changes

2024-07-03 13:48 UTC, nihal467 commented
@vigneshhari conditionally approving it for review alone by @sainak @rithviknishad & @vigneshhari, since ABDM fetched patient record takes some time to reflect in the platform (pending test)

2024-07-03 14:12 UTC, sainak requested changes

2024-07-03 14:12 UTC, sainak commented on care/abdm/api/viewsets/consent.py
> +            return Response(response.json(), status=response.status_code)
we had issues with abdm not actually responding with josn, we catch jsondecodeerror

2024-07-03 14:31 UTC, rithviknishad approved these changes

2024-07-04 11:21 UTC, sainak approved these changes

2024-07-08 07:46 UTC, nihal467 commented
LGTM

2024-08-21 09:50 UTC, rithviknishad approved these changes

2024-08-21 09:59 UTC, shivankacker approved these changes
LGTM, merge conflicts need to be resolved

2024-08-27 07:18 UTC, sainak approved these changes

2024-09-03 09:45 UTC, vigneshhari approved these changes
I have made a request for optimisation, resolve the merge conflicts as well.

2024-09-03 09:45 UTC, vigneshhari commented on care/abdm/api/viewsets/abha_number.py
> +    def get_queryset(self):
Can we rewrite the method to get the object first and then check for permission, The current query might be expensive to execute.

2024-09-06 04:14 UTC, sainak approved these changes

2024-09-06 08:29 UTC, merged