consultation depth backend
coronasafe/care pull request #2186
Opened 2024-05-21 08:49 UTC by sainak

## Proposed Changes

- convert symptoms filed to a separate table
- migrate existing symptoms to the new table
- Deprecate old symptom fields

### Associated Issue

- part of https://github.com/coronasafe/care_fe/issues/3618

### Architecture changes

- new symptoms table

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-05-21 10:24 UTC, rithviknishad requested changes
Unable to DELETE to set as entered in error. Stays in in-progress or completed.

<img width="447" alt="image" src="https://github.com/coronasafe/care/assets/25143503/8543b1ad-41a7-4004-950e-91af24d914f8">

<img width="676" alt="image" src="https://github.com/coronasafe/care/assets/25143503/771900c8-f3fc-4b49-9e27-aeb2fc4b8373">

2024-05-21 12:22 UTC, rithviknishad requested changes

2024-05-21 12:22 UTC, rithviknishad commented on care/facility/management/commands/load_event_types.py
> +            "model": "ConsultationSymptom",
```suggestion
            "model": "EncounterSymptom",
```

2024-05-22 06:25 UTC, rithviknishad approved these changes

2024-05-22 06:39 UTC, khavinshankar approved these changes

2024-05-22 16:06 UTC, nihal467 approved these changes

2024-05-22 16:06 UTC, nihal467 commented
LGTM tested through Tunnel

2024-05-28 10:38 UTC, vigneshhari approved these changes

2024-05-28 10:38 UTC, merged