migrating feature field  to array field
coronasafe/care pull request #2223
Opened 2024-06-03 06:40 UTC by DraKen0009

## Proposed Changes

Migrations sequence -
- renamed feature to old_feature
- added a feature field with array field
- copied data from old_feature field to feature field
- deleted old_feature field

### Associated Issue

- #2215 

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-06-03 14:19 UTC, sainak requested changes
we can remove old_features in a later pr

add the get__display

2024-06-03 14:19 UTC, sainak commented on care/facility/api/serializers/facility.py
> +    )
can you check if the validations are working 
- should not allow values not present in conices
- should not allow duplicates

2024-06-03 14:19 UTC, sainak commented on care/facility/migrations/0438_rename_features_facility_old_features.py
> +            facility.save()
use bulk update

2024-06-03 14:19 UTC, sainak commented on care/facility/migrations/0438_rename_features_facility_old_features.py
> +        ),
we can remove the field in a later pr

2024-06-03 14:19 UTC, sainak commented on care/facility/models/facility.py
>      )
add the get_features_display method as the array field doesn't register this getter

2024-06-03 18:17 UTC, praffq commented on care/facility/models/facility.py
>      )
```
    @property
    def get_features_display(self):
        if not self.features:
            return []
        return [REVERSE_FEATURE_CHOICES[f] for f in self.features]
```

something like this ?

2024-06-06 10:36 UTC, sainak commented on care/facility/models/facility.py
>      )
yes

2024-06-06 19:31 UTC, DraKen0009 commented
@sainak  made all the required changes, please take a look

2024-06-07 02:56 UTC, sainak commented on care/facility/models/facility.py
> +REVERSE_FEATURE_CHOICES = reverse_choices(FEATURE_CHOICES)
we can use a new integer choice enum `FacilityFeature`
keep the old one in place, just replace it for the new field

2024-07-10 10:00 UTC, sainak commented on care/facility/migrations/0438_rename_features_facility_old_features.py
> +        updated_facilities.append(facility)
```suggestion
        try:
            facility.features = list(map(int, facility.old_features.split(",")))
            updated_facilities.append(facility)
        except ValueError:
            print(f"facility '{facility.name)' has invalid facility features")
```

2024-07-10 10:00 UTC, sainak commented on care/facility/migrations/0438_rename_features_facility_old_features.py
update the migration number and remove the merge migrations

2024-07-11 03:55 UTC, rithviknishad approved these changes

2024-07-12 08:49 UTC, DraKen0009 commented
@sainak  @rithviknishad  made the changes , can you please run the workflows to check if everything's alright?

2024-07-12 10:55 UTC, rithviknishad requested changes

2024-07-12 10:55 UTC, rithviknishad commented on care/facility/migrations/0445_rename_features_facility_old_features.py
> +        ("facility", "0437_alter_dailyround_rounds_type"),
this needs to be changed to the previous migration before it

2024-07-12 10:55 UTC, rithviknishad commented on care/facility/migrations/0446_merge_20240712_1357.py
> +    operations = []
That way this merge migration can be deleted.

2024-07-13 17:17 UTC, praffq commented
updated. Should be fine now.

2024-07-20 08:21 UTC, DraKen0009 commented
@rithviknishad @sainak  I've fixed the errors , updated the migration file name and dependencies , also fixed the static dummy data from facility.json

2024-08-08 14:23 UTC, rithviknishad approved these changes

2024-08-16 14:10 UTC, sainak approved these changes

2024-08-21 18:05 UTC, vigneshhari approved these changes

2024-08-21 18:07 UTC, merged