Adds support for retrieving file uploads in doctore notes
coronasafe/care pull request #2291
Opened 2024-07-05 21:28 UTC by UdaySagar-Git

## Proposed Changes

- Adds support to retrieve uploaded files in doctor notes 

### Associated Issue

linked to the part of Frontend pr : https://github.com/coronasafe/care_fe/pull/8070

### Architecture changes

- Remove this section if not used

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-09-22 18:05 UTC, vigneshhari requested changes

2024-09-22 18:05 UTC, vigneshhari commented on care/facility/api/serializers/patient.py
> +    def get_files(self, obj):
This serves a lot of internal metadata about the row which is not needed.

2024-09-22 18:05 UTC, vigneshhari commented on care/facility/models/file_upload.py
> +        NOTES = 9, "NOTES"
How can we retrieve the files? there is no authz implemented for the same.

2024-10-01 23:41 UTC, UdaySagar-Git commented
@vigneshhari can you review this instead 
https://github.com/ohcnetwork/care/pull/2295

2024-10-15 14:59 UTC, closed without merging