Show error if doctor is not linked to the consultation facility
coronasafe/care pull request #2309
Opened 2024-07-17 14:26 UTC by skks1212

## Proposed Changes

- Brief of changes made.

### Associated Issue

- Link to issue here, explain how the proposed solution will solve the reported issue/ feature request.

### Architecture changes

- Remove this section if not used

## Merge Checklist

- [ ] Tests added/fixed
- [ ] Update docs in `/docs`
- [ ] Linting Complete
- [ ] Any other necessary step

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@coronasafe/care-backend-maintainers @coronasafe/care-backend-admins

2024-07-18 13:31 UTC, sainak requested changes

2024-07-18 13:31 UTC, sainak commented on care/facility/api/serializers/patient_consultation.py
> +                    "Oops! The treating doctor is no longer linked to this facility. Please update the respective field in the form before proceeding."
```suggestion
                    "The treating doctor is no longer linked to this facility. Please update the respective field in the form before proceeding."
```

2024-08-13 13:31 UTC, sainak approved these changes

2024-08-25 07:04 UTC, vigneshhari approved these changes

2024-08-25 07:28 UTC, merged