resolved issue #2383
coronasafe/care pull request #2452
Opened 2024-09-16 10:49 UTC by Dishaswamy

resolved #2383 

@ohcnetwork/care-backend-maintainers @ohcnetwork/care-backend-admins

2024-09-17 05:06 UTC, anroopak requested changes

2024-09-17 05:06 UTC, anroopak commented on care/facility/api/serializers/prescription.py
> +   def validate(self, attrs):
Please add valid test cases.

2024-09-17 05:06 UTC, anroopak commented on config/authentication.py
Changes in this file is not related to the mentioned issue. Please isolate this to a seperate PR.

2024-09-19 10:35 UTC, sainak commented
hey @Dishaswamy this prs has unrelated changes to files and the indentation is also incorrect,
read the following docs and open a new pr again:
https://docs.ohc.network/docs/contributing/
https://github.com/ohcnetwork/care/blob/develop/CONTRIBUTING.md

2024-09-19 10:35 UTC, closed without merging

2024-09-19 10:39 UTC, sainak commented
You should start working on a Pull request only when you are assigned the issue.