added test cases for asset bed
coronasafe/care pull request #2532
Opened 2024-10-13 00:46 UTC by DraKen0009

## Proposed Changes

- Added test cases for asset bed module
- Adding more test for bed create module
- Updated `PermissionError` with `PermissionDenied` for better handling of permission errors

### Associated Issue

- Fixes #1386 
- Part of #1372 

## Merge Checklist

- [x] Tests added/fixed
- [x] Linting Complete

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@ohcnetwork/care-backend-maintainers @ohcnetwork/care-backend-admins

2024-10-18 14:19 UTC, rithviknishad requested changes
Could you either merge or refactor the tests with this file? Recently few tests for asset bed has been added.

https://github.com/ohcnetwork/care/blob/develop/care/facility/tests/test_asset_bed_api.py

2024-10-22 13:57 UTC, rithviknishad approved these changes

2024-10-22 14:49 UTC, sainak approved these changes

2024-11-04 09:43 UTC, sainak approved these changes

2024-11-05 03:37 UTC, rithviknishad approved these changes

2024-11-14 14:15 UTC, merged