added check for email provider check before sending reset password email
coronasafe/care pull request #2544
Opened 2024-10-16 12:07 UTC by DraKen0009

## Proposed Changes

- Added a check to check if the email have valid configrations

### Associated Issue

- Fixes #1754 

![image](https://github.com/user-attachments/assets/5adc88eb-b4ab-40e1-a9ed-ba8b8d4a292d)

## Merge Checklist

- [x] Tests added/fixed
- [x] Linting Complete

_*Only PR's with test cases included and passing lint and test pipelines will be reviewed*_

@ohcnetwork/care-backend-maintainers @ohcnetwork/care-backend-admins

2024-10-16 12:48 UTC, vigneshhari requested changes

2024-10-16 12:48 UTC, vigneshhari commented on care/users/tests/test_auth.py
> +        EMAIL_HOST="smtp.gmail.com",
use a dummy host not something that could actually work.

2024-10-16 12:48 UTC, vigneshhari commented on care/users/tests/test_auth.py
> +        response = self.client.post(
We should mock the bits that actually send the email and confirm that the email has been sent.

2024-10-17 07:48 UTC, DraKen0009 commented
@vigneshhari  made the updates , Please take a look

2024-10-21 03:47 UTC, sainak approved these changes

2024-10-21 15:55 UTC, vigneshhari commented
Tests that check if the email was sent were still not added.

2024-10-21 15:56 UTC, merged