Labs
coronasafe/care pull request #2642
Opened 2024-12-09 07:12 UTC by khavinshankar

Added basic flow of creating a lab order till getting the results.

_Still filters and permissions are pending._

2024-12-09 07:31 UTC, vigneshhari commented on care/emr/resources/diagnostic_report/spec.py
> +            obj.save()
Dont call this here, if this is needed create a new abstraction for this.

2024-12-09 07:31 UTC, vigneshhari commented on care/emr/resources/service_request/spec.py
> +    code: Coding
Can be dict as well

2024-12-09 07:31 UTC, vigneshhari commented
@coderabbitai reivew

2025-01-09 07:33 UTC, vigneshhari requested changes
AuthZ missing, Add Tests and perform all coderabbit suggestions

2025-01-09 07:33 UTC, vigneshhari commented on care/emr/api/viewsets/diagnostic_report.py
> +    phase = ChoiceFilter(choices=PhaseChoices.choices, method="filter_phase")
We will not maintain any choices in care, all verbose values will be stored in the FE, the FE has to send the right values for filtering, remove the annotation as well.

2025-01-09 07:33 UTC, vigneshhari commented on care/emr/api/viewsets/diagnostic_report.py
> +    status = ChoiceFilter(
Remove

2025-01-09 07:33 UTC, vigneshhari commented on care/emr/api/viewsets/diagnostic_report.py
> +    create=extend_schema(request=DiagnosticReportCreateSpec),
Either add the response as well, or remove the extend_schema

2025-01-09 07:33 UTC, vigneshhari commented on care/emr/api/viewsets/diagnostic_report.py
> +        clean_data["performer"] = self.request.user.external_id
Set the value on perform_create and remove it from the spec for create and update

2025-01-09 07:33 UTC, vigneshhari commented on care/emr/api/viewsets/diagnostic_report.py
> +        data = DiagnosticReportObservationRequest(**request.data)
Keep this inside the viewset, right above this request

2025-01-09 07:33 UTC, vigneshhari commented on care/emr/api/viewsets/diagnostic_report.py
> +        for observation in data.observations:
Where is observation valueset validation?

2025-01-09 07:33 UTC, vigneshhari commented on care/emr/api/viewsets/specimen.py
> +        return queryset.annotate(
Maintain it as a calculated attribute or a filter, we will not do any annotation

2025-01-09 07:33 UTC, vigneshhari commented on care/facility/api/viewsets/facility.py
> +    geo_organization = GeoOrganizationFilter()
move this back

2025-01-09 07:33 UTC, vigneshhari commented on care/facility/api/viewsets/facility.py
> +    facility_type = filters.BaseInFilter(field_name="facility_type", lookup_expr="in")
Why was this changed here?

2025-01-10 17:54 UTC, khavinshankar commented on care/facility/api/viewsets/facility.py
> +    facility_type = filters.BaseInFilter(field_name="facility_type", lookup_expr="in")
This was updated to support filtering by multiple facility types, exact use case was to filter labs, both private and public
<img width="560" alt="image" src="https://github.com/user-attachments/assets/8d1a8852-465d-4c39-bed1-91ab1269dd70" />

2025-01-10 17:56 UTC, khavinshankar commented on care/emr/api/viewsets/diagnostic_report.py
> +        for observation in data.observations:
The observations are already validated by the specs
<img width="691" alt="image" src="https://github.com/user-attachments/assets/3ec03da5-bcee-4758-89c4-cb03974f817d" />

2025-01-10 17:58 UTC, khavinshankar commented on care/emr/models/specimen.py
> +    status = models.CharField(max_length=100, null=True, blank=True)
At the model level, its intensionally kept as a CharField for flexibility

2025-01-10 18:00 UTC, khavinshankar commented on care/emr/models/service_request.py
> +    priority = models.CharField(max_length=100, null=True, blank=True)
Intensional

2025-01-10 18:03 UTC, khavinshankar commented on care/emr/api/viewsets/specimen.py
> +from datetime import UTC, datetime
Yes, we are using python 3.13 and this was enforced by ruff

2025-01-10 18:13 UTC, khavinshankar commented on care/emr/models/service_request.py
> +    )
Not relevant, as none of these records will be hard deleted, they can only be soft deleted

2025-01-10 18:16 UTC, khavinshankar commented on care/emr/models/specimen.py
> +    received_at = models.DateTimeField(null=True, blank=True)
These are intensionally not added because in some cases, the specimen will be directly collected in the lab meaning the dispatched_at is null and received_at is set to now() (time of collection)

2025-02-18 13:43 UTC, closed without merging