Add last_daily_round to PatientConsultation
coronasafe/care pull request #660
Opened 2022-01-08 06:33 UTC by shaileshaanand

This PR adds last_daily_round to PatientConsultation as it is required to get bed details from patient consultation

2022-01-08 14:21 UTC, vigneshhari commented
Create a custom migration/ management command to update all the existing records.

2022-01-10 06:50 UTC, shaileshaanand commented
> Create a custom migration/ management command to update all the existing records.

@vigneshhari Added

2022-01-12 05:15 UTC, shaileshaanand commented
@vigneshhari I have updated the migration 0283 to use `bulk_update()`

2022-01-12 06:07 UTC, vigneshhari commented
@shaileshaanand Django's migrations has capability to move up or down the migration versions, use that to test the migration out.

2022-01-12 06:11 UTC, vigneshhari requested changes

2022-01-12 06:11 UTC, vigneshhari commented on care/facility/migrations/0283_populate_patientconsultation_last_daily_round.py
> +        ).order_by('-date').first()
Use **created_date** here

2022-01-12 06:11 UTC, vigneshhari commented
Make sure you test it out as well, once that's done we can merge in the change.

2022-01-12 12:05 UTC, shaileshaanand commented
> Make sure you test it out as well, once that's done we can merge in the change.

@vigneshhari I have tested it and it works, the modified date is not mutated as well.

2022-01-12 20:41 UTC, merged