Add Validation for Message
coronasafe/care pull request #683
Opened 2022-02-21 05:44 UTC by shrihari689

## 💪 Changes

- Minor Change in Validation

🔨 Issue associated with the Frontend: https://github.com/coronasafe/care_fe/pull/2123

2022-02-26 14:35 UTC, gigincg requested changes
Can you also fix the spelling for message? In the error response

2022-02-26 18:33 UTC, shrihari689 commented
Updated @gigincg  🚀

2022-03-24 07:23 UTC, gigincg commented
@shrihari689 Why did you remove  `or request.data["message"] == ""`

2022-03-30 05:08 UTC, shrihari689 commented
😲 I haven't removed it @gigincg 
📌 It's there on https://github.com/coronasafe/care/blob/ae1396463da27db295fb426658869700acc63416/care/facility/api/viewsets/notification.py#L57

2022-05-01 14:29 UTC, vigneshhari approved these changes

2022-05-01 14:29 UTC, vigneshhari commented on care/facility/api/viewsets/notification.py
> +        if "facility" not in request.data or request.data["facility"] == "":
Need more solid validation to check if the value is a UUID, but we'll build it later on.

2022-05-01 14:29 UTC, merged