Prevent creation of bed with the same name
coronasafe/care pull request #736
Opened 2022-05-11 14:43 UTC by iamsdas

Prevent the creation of a bed, if a bed with the same name exists in that location.
Fixes: [#2282](https://github.com/coronasafe/care_fe/issues/2282)

2022-05-14 14:53 UTC, vigneshhari requested changes
This validation should be written in the validate method, these validations can also be written at the model level which might make more sense.

2022-05-16 15:07 UTC, iamsdas commented
@vigneshhari
I updated the PR to add the validations in the model level (using the `clean` method) and made some minor changes so that DRF can handle these Django validation errors.

2022-06-19 13:06 UTC, vigneshhari approved these changes

2022-06-19 13:06 UTC, vigneshhari commented on care/facility/models/bed.py
> +        self.clean()
validate makes more sense here since you are not really cleaning anything.

2022-06-19 13:07 UTC, vigneshhari commented
resolve the conflicts and we are good to merge.

2022-07-03 19:34 UTC, vigneshhari approved these changes

2022-07-03 19:34 UTC, merged