Added soft delete API endpoint for file uploads
coronasafe/care pull request #740
Opened 2022-05-12 14:03 UTC by Marmik2003

Added soft delete API endpoint for issue https://github.com/coronasafe/care_fe/issues/2288

2022-05-22 09:46 UTC, vigneshhari commented
Only keep changes relevant to the PR, either remove the other changes or rebase with master if the changes are merged in

2022-05-22 09:48 UTC, vigneshhari requested changes

2022-05-22 09:48 UTC, vigneshhari commented on care/facility/api/viewsets/file_upload.py
> +        elif self.action == "destroy":
Why create a separate serializer?

2022-05-22 09:48 UTC, vigneshhari commented on care/facility/api/serializers/file_upload.py
> +class FileUploadDestroySerializer(serializers.ModelSerializer):
How exactly is this serializer supporting soft deletions?

2022-05-22 16:46 UTC, sainAk approved these changes

2022-05-22 16:47 UTC, sainAk commented
Ignore the review it was for a test

2022-05-22 16:50 UTC, sainAk approved these changes
This is a test review

2022-05-23 08:56 UTC, Marmik2003 commented
closing PR for removing unnecessary commits

2022-05-23 08:56 UTC, closed without merging