Make the meta field optional in Asset & Bed Tables
coronasafe/care pull request #769
Opened 2022-05-20 03:54 UTC by rabilrbl

Made meta field optional in Asset & Bed Tables

Closes #765

2022-05-26 11:01 UTC, vigneshhari commented
are you sure this wont break the fronend?

2022-05-27 17:07 UTC, sainAk requested changes

2022-05-27 17:07 UTC, sainAk commented on care/facility/models/asset.py
> +    meta = JSONField(null=True, blank=True)
To make the field optional making it nullable is not required
```suggestion
    meta = JSONField(default=dict, blank=True)
```

2022-05-27 17:07 UTC, sainAk commented on care/facility/models/bed.py
> +    meta = JSONField(null=True, blank=True)
```suggestion
    meta = JSONField(default=dict, blank=True)
```

2022-05-27 17:07 UTC, sainAk commented on care/facility/models/bed.py
> +    meta = JSONField(null=True, blank=True)
```suggestion
    meta = JSONField(default=dict, blank=True)
```

2022-05-27 17:07 UTC, sainAk commented on care/facility/models/bed.py
> +    meta = JSONField(null=True, blank=True)
```suggestion
    meta = JSONField(default=dict, blank=True)
```

2022-05-27 17:20 UTC, sainAk commented
@rabilrbl recreate the migrations

2022-05-27 18:04 UTC, sainAk approved these changes
LGTM

2022-06-19 12:50 UTC, merged

2022-06-19 12:52 UTC, vigneshhari commented
There is something wrong with the migrations, moving to temporary branch to test and push to master.