Fix error format for external test
coronasafe/care pull request #810
Opened 2022-06-01 14:07 UTC by Ashesh3

Required for https://github.com/coronasafe/care_fe/pull/2614

Just a minor change to how list of errors are sent to the client for the external test page.

2022-06-06 14:09 UTC, vigneshhari requested changes

2022-06-06 14:09 UTC, vigneshhari commented on care/facility/api/viewsets/patient_external_test.py
> +                errors.append(current_error)
Do you lose the context on what row has the error?

2022-06-22 06:30 UTC, Ashesh3 commented
@vigneshhari Any updates on this? :D

2022-07-03 19:32 UTC, vigneshhari approved these changes

2022-07-03 19:32 UTC, merged