Endpoint analyse/ fixed for read-only users
coronasafe/care pull request #814
Opened 2022-06-03 11:53 UTC by ishanExtreme

### Issue Fixed
fixes #813 

### Updates
The bug is because analyze is a post request
```
//viewset/daily_round.py line 49
@action(methods=["POST"], detail=False)
    def analyse(self, request, **kwargs):
```
and DailyRound model doesn't  allow POST,PUT,PATCH by read-only users
```
models/daily_round.py line 407  
@staticmethod
    def has_write_permission(request):
        if (
            request.user.user_type == User.TYPE_VALUE_MAP["DistrictReadOnlyAdmin"]
            or request.user.user_type == User.TYPE_VALUE_MAP["StateReadOnlyAdmin"]
            or request.user.user_type == User.TYPE_VALUE_MAP["StaffReadOnly"]
        ):
            return False
        return DailyRound.has_read_permission(request)
```
So adding an exception to /analyze route fixed the issue, we are still checking has_read_permission() to identify whether user is of same facility or not...

### Demo
![Screenshot from 2022-06-03 17-15-07](https://user-images.githubusercontent.com/39593226/171848503-b1d015d7-0ed8-456d-85bb-4ffa334e19a9.png)

2022-06-08 14:23 UTC, vigneshhari requested changes

2022-06-08 14:23 UTC, vigneshhari commented on care/facility/models/daily_round.py
> +        if(endpoint != "analyse"):
make the condition "/analyse" in request.get_full_path()

2022-06-10 09:45 UTC, ishanExtreme commented
![Screenshot from 2022-06-10 15-12-45](https://user-images.githubusercontent.com/39593226/173038923-e6012bb8-701a-44b7-a1a5-220d75cd1b77.png)

2022-06-10 18:12 UTC, vigneshhari approved these changes
Approved, Needs Sec Review!

2022-06-10 18:12 UTC, merged