add workflow to build and deploy docs
coronasafe/care pull request #826
Opened 2022-06-06 17:43 UTC by sainAk

closes #825

2022-06-06 18:09 UTC, vigneshhari requested changes

2022-06-06 18:09 UTC, vigneshhari commented on .github/workflows/docs.yml
> +  push:
we only need to build/deploy on the master branch

2022-06-07 12:22 UTC, Marmik2003 approved these changes
Looks good, i think it is ok if we don't remove sphinx from local requirements as some developers might also want to change the docs after few major changes!

2022-06-07 14:38 UTC, sainAk commented
> Looks good, i think it is ok if we don't remove sphinx from local requirements as some developers might also want to change the docs after few major changes!

I've refrenced the docs.txt requirements in local.txt so sphinx will also get installed in local environments

2022-06-08 10:21 UTC, vigneshhari approved these changes

2022-06-08 10:21 UTC, vigneshhari commented on .github/workflows/docs.yml
> +    if: github.ref == 'refs/heads/master'
Do we need this, this job only runs on pushes to master right?

2022-06-08 10:21 UTC, merged