Add check for empty comments and notes
coronasafe/care pull request #838
Opened 2022-06-08 12:33 UTC by Ashesh3

Builds on https://github.com/coronasafe/care_fe/pull/2525

Adds a check for empty comments and notes from the backend and rejects with proper validation message when needed.

Also some minor formatting change performed automatically by `pre-commit-hooks`

2022-06-08 12:54 UTC, sainAk requested changes
We can do this without regex

2022-06-08 13:19 UTC, Ashesh3 commented on care/facility/api/serializers/patient.py
> +        if not data.get("note") or re.match(r"^\s*$", data["note"]):
Changed to use strip in all 3 places, thanks!

2022-06-08 14:50 UTC, sainAk approved these changes
LGTM

2022-06-10 18:17 UTC, vigneshhari commented
I would create a new serializer field that has the empty check validator built-in and use that everywhere instead of re-writing the logic multiple times. Create a PR with this or create an issue to create such a field.

2022-06-10 18:18 UTC, vigneshhari approved these changes
Changes look good, Suggestions for the next iteration provided above, Untested.

2022-06-10 18:18 UTC, merged