Adding field validator for non-empty field
coronasafe/care pull request #853
Opened 2022-06-11 14:10 UTC by cp-Coder

# Updates

- [x] Fixes #849
- [x] Added `notEmptyValidator` to validate the object
- [ ] Modified serializers to validate the objects

2022-06-19 12:24 UTC, vigneshhari requested changes

2022-06-19 12:24 UTC, vigneshhari commented on care/utils/validation/not_empty.py
> +class notEmptyValidator:
follow class names patterns by [PEP 0008](https://peps.python.org/pep-0008/#class-names)

2022-06-19 12:24 UTC, vigneshhari commented on care/utils/validation/not_empty.py
> +        if not attrs[self.field].strip():
can there be a condition where attrs does not have the given field?

2022-06-19 12:24 UTC, vigneshhari commented on care/utils/validation/not_empty.py
> +from rest_framework import serializers
import ValidationError instead of importing the whole package

2023-05-07 08:22 UTC, cp-Coder commented
I don't think it is relevant now.

2023-05-07 08:22 UTC, closed without merging