prevent switching patient to the same bed
coronasafe/care pull request #854
Opened 2022-06-11 19:14 UTC by iamsdas

Prevent patients from switching to the same bed during consultation while the previous one hasn't ended.
fixes: #850

2022-06-12 04:55 UTC, iamsdas commented
before merging, do confirm if this was actually a bug and not some design consideration.

2022-06-14 14:11 UTC, iamsdas commented
Added commit for preventing bed switching after the patient has been discharged from care.

2022-06-19 12:18 UTC, vigneshhari requested changes

2022-06-19 12:18 UTC, vigneshhari commented on care/facility/api/serializers/bed.py
> +        if consultation.patient.is_active is False:
```suggestion
        if not consultation.patient.is_active:
```

2022-06-19 12:18 UTC, vigneshhari commented on care/facility/api/serializers/bed.py
> +                {"Patient:": ["Patient is already discharged from CARE"]})
```suggestion
                {"patient:": ["Patient is already discharged from CARE"]})
```

2022-06-19 12:18 UTC, vigneshhari commented on care/facility/api/serializers/bed.py
> +            raise ValidationError({"Bed:": ["Bed already in use by patient"]})
```suggestion
            raise ValidationError({"bed:": ["Bed already in use by patient"]})
```

2022-06-22 14:39 UTC, iamsdas commented
Added a commit to prevent switching to occupied beds (regardless of consultation).
Added it to address this [issue/comment](https://github.com/coronasafe/care/issues/850#issuecomment-1159448522).
This does not affect already existing multi-occupancies of beds. Should I add some kind of migration to handle them? (not sure how that would work though)

2022-07-06 18:16 UTC, vigneshhari approved these changes

2022-07-06 18:17 UTC, merged