Fixed Log update error
coronasafe/care pull request #892
Opened 2022-06-27 05:10 UTC by cp-Coder

# Updates

- [x] Fixes #879
- [x] Modified saving of `daily_round` object

2022-06-27 20:07 UTC, vigneshhari commented
wrap around transactions.

2022-07-03 19:47 UTC, vigneshhari approved these changes

2022-07-03 19:47 UTC, vigneshhari requested changes
Wrap around transactions

2022-07-04 07:40 UTC, cp-Coder commented
@vigneshhari In this change alright??

2022-07-04 14:16 UTC, vigneshhari approved these changes

2022-07-04 14:16 UTC, merged