updated message when token is not valid
coronasafe/care pull request #906
Opened 2022-07-02 09:05 UTC by Marmik2003

fixes https://github.com/coronasafe/care_fe/issues/2964

2022-07-02 10:19 UTC, sainAk requested changes
This auth class is used for middlewares its not used by the front-end to change the message, You need to override  `get_validated_token` in `CustomJWTAuthentication` where you need to catch `InvalidToken` and re raise it with a different messege.

2022-07-02 11:02 UTC, sainAk requested changes
Override this auth class
https://github.com/coronasafe/care/blob/master/config/settings/base.py#L302

2022-07-03 05:37 UTC, sainAk commented on config/authentication.py
> +        )
```suggestion
            return super().get_validated_token(raw_token)
        except InvalidToken as e:
            raise InvalidToken({
                "detail": "Invalid Token, please relogin to continue",
                "messages" : e.detail.get("messages", [])
            }) from e
```

2022-07-03 05:40 UTC, sainAk approved these changes

2022-07-03 19:30 UTC, vigneshhari approved these changes

2022-07-03 19:30 UTC, merged