Fixes: Permission Error during Facility Delete
coronasafe/care pull request #976
Opened 2022-08-10 15:23 UTC by cp-Coder

# Updates

- [x] Closes #975
- [x] Added `has_destroy_permission` method for permission checking
- [x] Updated the logic of `has_write_permission` method
- [x] Formatted the code

2022-08-11 06:16 UTC, Ashesh3 approved these changes

2022-08-12 14:31 UTC, cp-Coder commented
I have removed  permissions for facility deletion

2022-08-12 14:32 UTC, cp-Coder commented
I have removed `LocalBodyAdmin` permissions for facility deletion

2022-09-07 11:40 UTC, vigneshhari requested changes

2022-09-07 11:40 UTC, vigneshhari commented on care/facility/models/mixins/permissions/facility.py
> +            print(e)
Lets remove these logging statements

2022-10-02 15:33 UTC, cp-Coder commented
@vigneshhari Any suggestion regarding this PR?

2022-10-09 05:04 UTC, closed without merging